version: "3"
services:

  sql-server:
    build: ./database
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: StrongP@ssword!

  cpu-server:
    build: ./server
    ports:
      - 80:80
      
  cpu-client:
    build: ./client
    ports:
      - "8888:80"