version: "3"
services:

  proxy:
    image: nginx
    volumes:
      - ./proxy/:/etc/nginx/templates/
    ports:
      - "${FRONT_END_PORT}:80"
      
  sql-server:
    build: ./database
    environment:
      SA_PASSWORD: "${DB_PASSWORD}"

  cpu-server:
    build: ./server
    environment:
      SA_PASSWORD: "${DB_PASSWORD}"
      FRONT_END_URL: "${FRONT_END_HOST}:${FRONT_END_PORT}"

  cpu-client:
    build: ./client
    environment:
      BACKEND_API_URL: "${BACKEND_API_URL}"